/** Production-browser acceptance on an isolated Ethereum fork. All writes are signed
 * with ephemeral fixture keys and sent exclusively to this process's loopback Anvil. */
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createServer as netServer} from 'node:net';
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {resolve,dirname,extname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {createPublicClient,createWalletClient,http,parseEther,formatEther,parseAbi,toHex,decodeFunctionData} from 'viem';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {mainnet} from 'viem/chains';
const root=resolve(process.env.PRISM_REVIEW_ROOT||resolve(dirname(fileURLToPath(import.meta.url)),'../..'));
const artifacts=resolve(root,'artifacts/financial-browser');await mkdir(artifacts,{recursive:true});
const token='0xfd1c234972768c23bb21d655966e0b122dd67a2c',vault='0x10373c4afc7851b8ab5d94dce7ec1688624cec33',owner='0x13afb9b5780cd9ae79c61503adb69c57845d8eac',router='0x66a9893cc07d91d95644aedd05d03f95e1dba8af',permit2='0x000000000022d473030f116ddee9f6b43ac78ba3';
const tokenAbi=JSON.parse(await readFile(resolve(root,'web/src/chain/abi/PrismRiotToken.json'))),vaultAbi=JSON.parse(await readFile(resolve(root,'web/src/chain/abi/StakingVault.json')));
const p2abi=parseAbi(['function allowance(address,address,address) view returns(uint160,uint48,uint48)']);
const upstreamUrl=process.env.PRISM_FORK_RPC||'https://ethereum-rpc.publicnode.com';
const upstream=createPublicClient({chain:mainnet,transport:http(upstreamUrl,{timeout:30000})});
const forkBlock=await upstream.getBlockNumber();
const ns=netServer();await new Promise(r=>ns.listen(0,'127.0.0.1',r));const port=ns.address().port;await new Promise(r=>ns.close(r));
const endpoint=`http://127.0.0.1:${port}`;
const anvil=spawn(process.env.PRISM_ANVIL||'anvil',['--fork-url',upstreamUrl,'--fork-block-number',String(forkBlock),'--chain-id','1','--host','127.0.0.1','--port',String(port),'--threads','4','--fork-state-by-number','--no-fork-node-info','--timeout','10000','--retries','1','--silent'],{stdio:['ignore','pipe','pipe']});let anvilError='',anvilOutputBytes=0;anvil.stdout.on('data',b=>{anvilOutputBytes+=b.length;});anvil.stderr.on('data',b=>{anvilError=(anvilError+b.toString()).slice(-8000);});
const local=createPublicClient({chain:mainnet,transport:http(endpoint,{timeout:60000,retryCount:0}),cacheTime:0,pollingInterval:100});
const rpc=(method,params=[])=>local.request({method,params});
const identities=[privateKeyToAccount(generatePrivateKey()),privateKeyToAccount(generatePrivateKey()),privateKeyToAccount(generatePrivateKey()),privateKeyToAccount(generatePrivateKey())];
const wallets=identities.map(account=>createWalletClient({account,chain:mainnet,transport:http(endpoint)}));
const report={date:new Date().toISOString(),forkBlock:String(forkBlock),exportPath:'/preview/',checks:[],transactions:[],screenshots:[],pageErrors:[],resourceFailures:[],consoleErrors:[],limitations:['Ethereum fork only. No transaction was broadcast to mainnet.','Controlled injected provider with ephemeral signing keys; not a physical wallet extension or device.','Screen-reader, native browser zoom and 10%-speed animation replay were not performed.']};
const rpcFailures=[];
let browser,server,page,ctx,failRpc=false,failPrimary=false,failGames=false,delayQuote=0,windowGuardDelay=false,corruptVault=false,staleBlocks=false;
const save=async name=>{const path=resolve(artifacts,name);await page.screenshot({path,type:'jpeg',quality:60});report.screenshots.push(name);};
const check=async(name,fn)=>{const start=Date.now();try{const detail=await fn();report.checks.push({name,passed:true,ms:Date.now()-start,detail});console.log('PASS '+name);}catch(e){report.checks.push({name,passed:false,error:String(e.stack||e),ms:Date.now()-start});console.log('FAIL '+name+': '+e.message);console.log('RPC failures: '+JSON.stringify(rpcFailures.slice(-8)));console.log('Anvil: '+anvilError.slice(-1500));await save('failure-'+report.checks.length+'.jpg').catch(()=>{});await page?.keyboard.press('Escape').catch(()=>{});}};
const balance=address=>local.readContract({address:token,abi:tokenAbi,functionName:'balanceOf',args:[address]});
const staked=address=>local.readContract({address:vault,abi:vaultAbi,functionName:'staked',args:[address]});
const swap=()=>page.locator('#buy');const primary=()=>swap().locator('.button.primary').first();
const waitEnabled=async locator=>{await locator.waitFor({state:'visible'});await page.waitForFunction(e=>!e.disabled,await locator.elementHandle(),{timeout:90000});};
const waitReceipt=async scope=>{await scope.getByText('Transaction confirmed',{exact:true}).waitFor({timeout:90000});await scope.getByText('Transaction in progress…',{exact:true}).waitFor({state:'hidden',timeout:90000});};
async function refreshSwap(){await waitEnabled(swap().getByRole('button',{name:'Refresh balances / retry RPC',exact:true}));await swap().getByRole('button',{name:'Refresh balances / retry RPC',exact:true}).click();await swap().getByRole('button',{name:'Refresh balances / retry RPC',exact:true}).waitFor({timeout:90000});}
async function openStake(){await page.locator('.main-nav').getByRole('button',{name:'Staking',exact:true}).click();const d=page.getByRole('dialog');await d.locator('.stake-panel').waitFor();await d.getByText('No reward stream is currently active',{exact:true}).waitFor({timeout:90000});return d;}
async function connect(){await page.getByRole('button',{name:'Open wallet',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Connect wallet',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Disconnect',exact:true}).waitFor();await page.keyboard.press('Escape');}
try {
 for(let i=0;i<80;i++){try{if(String(await rpc('web3_clientVersion')).toLowerCase().includes('anvil'))break;}catch{}if(i===79)throw Error('Anvil unavailable '+anvilError);await new Promise(r=>setTimeout(r,250));}
 assert.match(endpoint,/^http:\/\/127\.0\.0\.1:/);assert.match(String(await rpc('web3_clientVersion')),/anvil/i);
 for(const account of identities.slice(0,2))await rpc('anvil_setBalance',[account.address,toHex(parseEther('.05'))]);
 // Warm the fork's upstream code/storage cache before applying production RPC timeouts.
 // This changes no contract storage and does not replace any browser read/verification.
 const warmStart=Date.now(),warmContracts=[];
 for(const [address,name] of [[token,'PrismRiotToken'],[vault,'StakingVault'],['0x65a783cc6725a02ce349dc4d72577994df1760cc','TreasuryFeeHook'],['0xb68b1ba47734ba91f3fc37164bb39d408908ff7c','FeeTreasury'],['0xe31277d4e9fbf9fc35239dc7d2280e97d5c817c1','Arena'],['0x002021b4aeb4125ff25e0353b004f6fdec5f93ed','OracleAdapter']]){
   const abi=JSON.parse(await readFile(resolve(root,`web/src/chain/abi/${name}.json`)));
   for(const item of abi.filter(a=>a.type==='function'&&['view','pure'].includes(a.stateMutability)&&a.inputs.length===0))warmContracts.push({address,abi,functionName:item.name});
 }
 console.log('Warming local fork code and view storage');
 await local.multicall({contracts:warmContracts,allowFailure:true});
 for(const address of [router,permit2,'0x000000000004444c5dc75cb358380d2e3de08a90','0x52f0e24d1c21c8a0cb1e5a5dd6198556bd9e1203','0x7ffe42c4a5deea5b0fec41c94c136cf115597227'])await local.getCode({address});
 for(const identity of identities){await local.getBalance({address:identity.address});await balance(identity.address);await staked(identity.address);await local.readContract({address:token,abi:tokenAbi,functionName:'allowance',args:[identity.address,permit2]});await local.readContract({address:token,abi:tokenAbi,functionName:'allowance',args:[identity.address,vault]});await local.readContract({address:permit2,abi:p2abi,functionName:'allowance',args:[identity.address,token,router]});}
 report.warmupMs=Date.now()-warmStart;console.log(`Fork warmup complete in ${report.warmupMs}ms`);

 const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.woff2':'font/woff2'};
 server=createServer(async(req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!pathname.startsWith('/preview/'))throw Error();const path=resolve(root,'dist',pathname.slice(9)||'index.html');if(!path.startsWith(resolve(root,'dist')+sep))throw Error();const body=await readFile(path);res.writeHead(200,{'Content-Type':mime[extname(path)]||'application/octet-stream','Cache-Control':'no-store'});res.end(body);}catch{res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/preview/`;
 browser=await chromium.launch({headless:true,args:['--no-sandbox'],executablePath:process.env.PRISM_REVIEW_CHROMIUM||'/root/.cache/ms-playwright/chromium-1246/chrome-linux64/chrome'});report.browser=browser.version();ctx=await browser.newContext({viewport:{width:1440,height:1000}});
 await ctx.exposeBinding('__forkSign',async(_,tx)=>{
   const signer=wallets.find(w=>w.account.address.toLowerCase()===tx.from.toLowerCase());assert.ok(signer,'Only ephemeral fixture accounts may sign');assert.equal(await local.getChainId(),1);assert.match(String(await rpc('web3_clientVersion')),/anvil/i);
   const request={to:tx.to,data:tx.data,value:BigInt(tx.value||0),...(tx.gas?{gas:BigInt(tx.gas)}:{}),...(tx.maxFeePerGas?{maxFeePerGas:BigInt(tx.maxFeePerGas)}:{}),...(tx.maxPriorityFeePerGas?{maxPriorityFeePerGas:BigInt(tx.maxPriorityFeePerGas)}:{})};
   const hash=await signer.sendTransaction(request);const receipt=await local.waitForTransactionReceipt({hash});report.transactions.push({hash,to:tx.to,value:String(request.value),status:receipt.status,block:String(receipt.blockNumber),network:'local fork only'});return hash;
 });
 await ctx.addInitScript(({accounts,owner})=>{
   localStorage.setItem('prism-language','tr');window.__walletState={account:accounts[0],chain:'0x1',locked:false,failSwitch:false,rejectNext:false,requests:[],signatures:0};
   const make=(index)=>{const listeners={};const p={on:(e,f)=>(listeners[e]??=[]).push(f),removeListener:(e,f)=>listeners[e]=(listeners[e]||[]).filter(x=>x!==f),request:async({method,params})=>{const w=window.__walletState;w.requests.push(method);if(method==='eth_accounts'||method==='eth_requestAccounts'){if(w.locked&&method==='eth_requestAccounts')throw {code:4100,message:'Wallet locked. Unlock and reconnect.'};return w.locked?[]:[index===0?w.account:accounts[1]];}if(method==='eth_chainId')return w.chain;if(method==='wallet_switchEthereumChain'){if(!w.failSwitch){w.chain=params[0].chainId;(listeners.chainChanged||[]).forEach(f=>f(w.chain));}return null;}if(method==='eth_sendTransaction'){w.signatures++;if(w.rejectNext){w.rejectNext=false;throw {code:4001,message:'User rejected request'};}return window.__forkSign(params[0]);}throw Error('Unsupported controlled-wallet method '+method);}};p.emit=(e,v)=>(listeners[e]||[]).forEach(f=>f(v));return p;};
   const providers=[make(0),make(1)];window.ethereum=providers[0];window.__changeWallet=(account,chain='0x1')=>{window.__walletState.account=account;window.__walletState.chain=chain;providers[0].emit('accountsChanged',[account]);providers[0].emit('chainChanged',chain);};window.__lock=()=>{window.__walletState.locked=true;providers[0].emit('accountsChanged',[]);};window.__emitAccount=()=>providers[0].emit('accountsChanged',[window.__walletState.account]);window.__testAccounts=accounts;window.__owner=owner;
   window.addEventListener('eip6963:requestProvider',()=>providers.forEach((provider,i)=>window.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{rdns:`local.fixture.${i}`,name:`Fork wallet ${i+1}`,uuid:`fork-${i}`},provider}}))));
 },{accounts:identities.map(a=>a.address),owner});
 await ctx.route(/https:\/\/(ethereum-rpc\.publicnode\.com|eth\.drpc\.org)/,async route=>{
   const body=route.request().postDataJSON(),requests=Array.isArray(body)?body:[body];
   const responses=await Promise.all(requests.map(async r=>{try{
     assert.ok(['eth_call','eth_getCode','eth_chainId','eth_getBalance','eth_blockNumber','eth_getBlockByNumber','eth_getBlockByHash','eth_getLogs','eth_getTransactionReceipt','eth_estimateGas','eth_gasPrice','eth_maxPriorityFeePerGas','eth_feeHistory','eth_getTransactionByHash','eth_getTransactionCount'].includes(r.method),'No writes allowed via public transport');
     if(failRpc||(failPrimary&&route.request().url().includes('publicnode')))throw Error('Controlled RPC outage; retry available');
     if(failGames&&(r.method==='eth_call')&&JSON.stringify(r.params).toLowerCase().includes('002021b4aeb4125ff25e0353b004f6fdec5f93ed'))throw Error('Unrelated game adapter read unavailable');
     if(corruptVault&&r.method==='eth_getCode'&&r.params[0].toLowerCase()===vault)return {jsonrpc:'2.0',id:r.id,result:'0x6000'};
     if(windowGuardDelay&&r.method==='eth_call'&&r.params?.[0]?.to?.toLowerCase()===router)await new Promise(r=>setTimeout(r,1500));
     if(delayQuote&&r.method==='eth_call'&&JSON.stringify(r.params).toLowerCase().includes('52f0e24d1c21c8a0cb1e5a5dd6198556bd9e1203'))await new Promise(r=>setTimeout(r,delayQuote));
     const result=await rpc(r.method,r.params);if(staleBlocks&&['eth_getBlockByNumber','eth_getBlockByHash'].includes(r.method)&&result?.timestamp)result.timestamp=toHex(BigInt(result.timestamp)-601n);return {jsonrpc:'2.0',id:r.id,result};
   }catch(e){rpcFailures.push({method:r.method,error:String(e.message).slice(0,300)});return {jsonrpc:'2.0',id:r.id,error:{code:-32000,message:e.message}};}}));
   await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(Array.isArray(body)?responses:responses[0])});
 });
 page=await ctx.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>report.pageErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('response',r=>{if(r.url().startsWith(url)&&r.status()>=400)report.resourceFailures.push({url:r.url(),status:r.status()});});await page.goto(url);
 await check('English-only production export ignores and removes saved Turkish preference',async()=>{await swap().locator('input[name="swap-amount"]').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.evaluate(()=>localStorage.getItem('prism-language')),null);assert.equal(await page.locator('.language-toggle').count(),0);assert.doesNotMatch(await page.locator('body').innerText(),/[ğĞıİşŞçÇöÖüÜ]/);assert.equal(await swap().locator('input[name="swap-amount"]').inputValue(),'');assert.equal(await swap().getByRole('button',{name:'Buy PRIO',exact:true}).getAttribute('aria-pressed'),'true');});
 await check('Buying is immediately visible; desktop and mobile export reflow',async()=>{const views=[];for(const width of [1440,850,390,320]){await page.setViewportSize({width,height:width<500?844:1000});await page.evaluate(()=>scrollTo(0,0));const result=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,hero:document.querySelector('.hero').getBoundingClientRect().bottom,buy:document.querySelector('#buy').getBoundingClientRect().top,buyNav:document.querySelector('.nav-buy').getBoundingClientRect().width}));assert.ok(result.scrollWidth<=width);assert.ok(result.buyNav>0);if(width===1440)assert.ok(result.buy<400);if(width<1200)assert.ok(result.buy>=result.hero-1&&result.buy<=result.hero+10);views.push(result);if([1440,390].includes(width))await save(`hero-${width}.jpg`);}return views;});
 await page.setViewportSize({width:1440,height:1000});
 await check('Connection uses account access only and supports multiple injected providers',async()=>{await connect();assert.equal(await page.evaluate(()=>window.__walletState.signatures),0);assert.equal(await page.locator('.founder-section').count(),0);await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));return {providerCount:await page.evaluate(()=>window.__walletState.requests.filter(x=>x==='eth_requestAccounts').length)};});
 await check('Selecting a second injected provider disconnects first and uses only selected wallet',async()=>{await page.getByRole('button',{name:'Open wallet',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('Wallet provider').selectOption('local.fixture.1');await d.getByRole('button',{name:'Connect wallet',exact:true}).click();await d.getByRole('button',{name:'Disconnect',exact:true}).waitFor();assert.match(await d.innerText(),new RegExp(identities[1].address.slice(0,6),'i'));await d.getByLabel('Wallet provider').selectOption('local.fixture.0');await d.getByRole('button',{name:'Connect wallet',exact:true}).click();await d.getByRole('button',{name:'Disconnect',exact:true}).waitFor();await page.keyboard.press('Escape');});
 await check('Invalid amount, zero token balance and explicit quote preparation blockers',async()=>{for(const v of ['-1','0','1e3','1,000','0.0000000000000000001']){await swap().locator('[name="swap-amount"]').fill(v);await page.waitForTimeout(30);assert.match(await swap().locator('#swap-help').innerText(),/Invalid amount/);assert.equal(await primary().isDisabled(),true);}await swap().getByRole('button',{name:'Sell PRIO',exact:true}).click();await swap().locator('[name="swap-amount"]').fill('100');await page.getByText('Insufficient PRIO balance. Reduce the amount or add funds.',{exact:true}).waitFor();assert.equal(await primary().isDisabled(),true);await swap().getByRole('button',{name:'Buy PRIO',exact:true}).click();assert.equal(await swap().locator('[name="swap-amount"]').inputValue(),'');});
 await check('ETH percentage shortcuts reserve freshly estimated gas, round down, and never sign',async()=>{await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));const before=await page.evaluate(()=>window.__walletState.signatures);for(const percentage of [25,50,75,100]){const label=percentage===100?'MAX':percentage+'%';await waitEnabled(swap().getByRole('button',{name:label,exact:true}));await swap().getByRole('button',{name:label,exact:true}).click();const amount=parseEther(await swap().locator('[name="swap-amount"]').inputValue());const eth=await local.getBalance({address:identities[0].address});assert.ok(amount>0n&&amount<eth*BigInt(percentage)/100n);assert.equal(await swap().getByRole('button',{name:label,exact:true}).getAttribute('aria-pressed'),'true');}assert.equal(await page.evaluate(()=>window.__walletState.signatures),before);await swap().locator('[name="swap-amount"]').fill('.001');assert.equal(await swap().locator('.amount-shortcuts [aria-pressed="true"]').count(),0);await swap().locator('[name="swap-amount"]').fill('0.001');});
 await check('Debounced quote races discard old amounts and keep protected minimum output',async()=>{delayQuote=500;await swap().locator('[name="swap-amount"]').fill('0.002');await page.waitForTimeout(600);await swap().locator('[name="swap-amount"]').fill('0.001');await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));delayQuote=0;assert.equal(await swap().locator('[name="swap-amount"]').inputValue(),'0.001');assert.doesNotMatch(await swap().locator('.swap-output').innerText(),/—/);assert.match(await swap().locator('.gas-note').innerText(),/25%.*20%/);});
 await check('Wallet rejection preserves the quote and never reports confirmation',async()=>{await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));await page.evaluate(()=>window.__walletState.rejectNext=true);const count=report.transactions.length;await swap().getByRole('button',{name:'Review buy in wallet',exact:true}).click();await swap().getByRole('alert').filter({hasText:'declined'}).waitFor();assert.equal(report.transactions.length,count);assert.equal(await swap().getByText('Transaction confirmed',{exact:true}).count(),0);});
 await check('Buy routes through deployed router simulation and a signed local transaction',async()=>{const before=await balance(identities[0].address);await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));await swap().getByRole('button',{name:'Review buy in wallet',exact:true}).click();await waitReceipt(swap());const after=await balance(identities[0].address);assert.ok(after>before);assert.equal(report.transactions.at(-1).to.toLowerCase(),router);assert.equal(await swap().locator('[name="swap-amount"]').inputValue(),'');return {receivedPrioBaseUnits:String(after-before),transaction:report.transactions.at(-1).hash};});
 await check('Sell percentages use wallet PRIO; exact token and Permit2 allowances lead to sell',async()=>{await swap().getByRole('button',{name:'Sell PRIO',exact:true}).click();await waitEnabled(swap().getByRole('button',{name:'25%',exact:true}));const available=await balance(identities[0].address);for(const n of [25,50,75,100]){await swap().getByRole('button',{name:n===100?'MAX':n+'%',exact:true}).click();assert.equal(parseEther(await swap().locator('[name="swap-amount"]').inputValue()),available*BigInt(n)/100n);}await swap().locator('[name="swap-amount"]').fill('100');await waitEnabled(swap().getByRole('button',{name:'Approve exact PRIO',exact:true}));const before=report.transactions.length;await swap().getByRole('button',{name:'Approve exact PRIO',exact:true}).click();await waitReceipt(swap());assert.equal(report.transactions.length-before,2);assert.equal(await local.readContract({address:token,abi:tokenAbi,functionName:'allowance',args:[identities[0].address,permit2]}),parseEther('100'));const [allowance,expiry]=await local.readContract({address:permit2,abi:p2abi,functionName:'allowance',args:[identities[0].address,token,router]});assert.equal(allowance,parseEther('100'));assert.ok(expiry<=Number((await local.getBlock()).timestamp)+1200);await waitEnabled(swap().getByRole('button',{name:'Review sell in wallet',exact:true}));await swap().locator('[name="swap-amount"]').fill('101');await waitEnabled(swap().getByRole('button',{name:'Approve exact PRIO',exact:true}));await swap().locator('[name="swap-amount"]').fill('100');await waitEnabled(swap().getByRole('button',{name:'Review sell in wallet',exact:true}));const prio=await balance(identities[0].address);await swap().getByRole('button',{name:'Review sell in wallet',exact:true}).click();await waitReceipt(swap());assert.equal(prio-await balance(identities[0].address),parseEther('100'));});
 await check('Zero-reward staking allows exact approval and deposit with actual wallet blockers',async()=>{const d=await openStake();assert.doesNotMatch(await d.innerText(),/Deposits work/);assert.match(await d.innerText(),/Your claimable rewards\n0 PRIO/);const available=await balance(identities[0].address);for(const n of [25,50,75,100]){await d.getByRole('button',{name:n===100?'MAX':n+'%',exact:true}).click();assert.equal(parseEther(await d.locator('[name="staking-amount"]').inputValue()),available*BigInt(n)/100n);}await d.locator('[name="staking-amount"]').fill('123.000000000000000003');assert.equal(await d.locator('.amount-shortcuts [aria-pressed="true"]').count(),0);await waitEnabled(d.getByRole('button',{name:'Approve exact PRIO for staking',exact:true}));await d.getByRole('button',{name:'Approve exact PRIO for staking',exact:true}).click();await waitReceipt(d);const amount=parseEther('123.000000000000000003');assert.equal(await local.readContract({address:token,abi:tokenAbi,functionName:'allowance',args:[identities[0].address,vault]}),amount);await waitEnabled(d.getByRole('button',{name:'Review deposit in wallet',exact:true}));await d.getByRole('button',{name:'Review deposit in wallet',exact:true}).click();await waitReceipt(d);assert.equal(await staked(identities[0].address),amount);assert.equal(await d.getByRole('button',{name:'Claim funded rewards',exact:true}).isDisabled(),true);assert.match(await d.locator('#claim-help').innerText(),/nothing to claim/);await save('staking-desktop.jpg');});
 await check('Withdraw percentage rounds down from own principal and confirms withdrawal',async()=>{const d=page.getByRole('dialog');await d.getByRole('button',{name:'Withdraw PRIO',exact:true}).click();const principal=await staked(identities[0].address);for(const n of [25,50,75,100]){await d.getByRole('button',{name:n===100?'MAX':n+'%',exact:true}).click();assert.equal(parseEther(await d.locator('[name="staking-amount"]').inputValue()),principal*BigInt(n)/100n);}await d.getByRole('button',{name:'25%',exact:true}).click();await waitEnabled(d.getByRole('button',{name:'Review withdrawal in wallet',exact:true}));await d.getByRole('button',{name:'Review withdrawal in wallet',exact:true}).click();await waitReceipt(d);assert.equal(await staked(identities[0].address),principal-principal/4n);await page.keyboard.press('Escape');});
 await check('Disconnect during asynchronous simulation invalidates the captured signing client',async()=>{
 await page.keyboard.press('Escape');await swap().getByRole('button',{name:'Buy PRIO',exact:true}).click();await swap().locator('[name="swap-amount"]').fill('0.001');await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));
 const before=report.transactions.length;windowGuardDelay=true;try { await swap().getByRole('button',{name:'Review buy in wallet',exact:true}).click();await page.getByRole('button',{name:'Open wallet',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Disconnect',exact:true}).click();await page.keyboard.press('Escape');await swap().getByRole('alert').filter({hasText:/session changed|account changed/}).waitFor({timeout:30000});assert.equal(report.transactions.length,before); } finally {windowGuardDelay=false;await connect();}
 });
 await check('Disconnect followed by accountsChanged cannot restore an account without a client',async()=>{await page.getByRole('button',{name:'Open wallet',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Disconnect',exact:true}).click();await page.evaluate(()=>window.__emitAccount());await page.waitForTimeout(300);assert.match(await page.getByRole('dialog').innerText(),/Connect your wallet for real transactions/);assert.equal(await page.getByRole('dialog').getByRole('button',{name:'Disconnect',exact:true}).count(),0);await page.getByRole('dialog').getByRole('button',{name:'Connect wallet',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Disconnect',exact:true}).waitFor();await page.keyboard.press('Escape');});
 await check('Restoration recreates wallet client without prompting or signing',async()=>{await page.reload();await swap().locator('input[name="swap-amount"]').waitFor();await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));assert.equal(await page.evaluate(()=>window.__walletState.requests.includes('eth_requestAccounts')),false);assert.equal(await page.evaluate(()=>window.__walletState.signatures),0);const d=await openStake();await d.locator('[name="staking-amount"]').fill('1');await waitEnabled(d.getByRole('button',{name:'Approve exact PRIO for staking',exact:true}));await page.keyboard.press('Escape');});
 await check('Locked wallet clears connected state and provides unlock/reconnect recovery',async()=>{await page.evaluate(()=>window.__lock());await page.getByRole('button',{name:'Open wallet',exact:true}).click();await page.getByRole('dialog').getByText('Connect your wallet for real transactions.',{exact:true}).waitFor();assert.match(await page.getByRole('dialog').innerText(),/locked|Unlock/i);await page.getByRole('dialog').getByRole('button',{name:'Connect wallet',exact:true}).click();assert.match(await page.getByRole('dialog').innerText(),/locked/i);await page.evaluate(()=>window.__walletState.locked=false);await page.getByRole('dialog').getByRole('button',{name:'Connect wallet',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Disconnect',exact:true}).waitFor();await page.keyboard.press('Escape');});
 await check('Wrong chain clears input and failed network switch never reports Ethereum success',async()=>{await swap().locator('[name="swap-amount"]').fill('0.001');await page.evaluate(()=>window.__changeWallet(window.__walletState.account,'0x2105'));await swap().getByText('Wrong network. Switch your wallet to Ethereum.',{exact:true}).waitFor();assert.equal(await swap().locator('[name="swap-amount"]').inputValue(),'');await page.evaluate(()=>window.__walletState.failSwitch=true);await swap().getByRole('button',{name:'Switch to Ethereum',exact:true}).first().click();await swap().getByText(/did not switch/).waitFor();assert.equal(await page.evaluate(()=>window.__walletState.chain),'0x2105');await page.evaluate(()=>window.__walletState.failSwitch=false);await swap().getByRole('button',{name:'Switch to Ethereum',exact:true}).first().click();await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));});
 await check('Account changes invalidate inputs, balances, quotes and approval assumptions',async()=>{await swap().locator('[name="swap-amount"]').fill('0.001');await page.evaluate(()=>window.__changeWallet(window.__testAccounts[1]));await page.waitForFunction(()=>document.querySelector('.wallet-button').innerText.includes(window.__testAccounts[1].slice(0,6)));assert.equal(await swap().locator('[name="swap-amount"]').inputValue(),'');await swap().getByRole('button',{name:'Sell PRIO',exact:true}).click();await swap().locator('[name="swap-amount"]').fill('1');await swap().getByText('Insufficient PRIO balance. Reduce the amount or add funds.',{exact:true}).waitFor();assert.equal(await primary().isDisabled(),true);await page.evaluate(()=>window.__changeWallet(window.__testAccounts[0]));await swap().getByRole('button',{name:'Buy PRIO',exact:true}).click();});
 await check('Fallback RPC, full outage and explicit retry recovery',async()=>{failPrimary=true;await refreshSwap();assert.doesNotMatch(await swap().locator('#swap-help').innerText(),/RPC read failed/);failRpc=true;await refreshSwap();await swap().getByText(/RPC read failed/).waitFor({timeout:90000});assert.equal(await swap().getByRole('button',{name:'MAX',exact:true}).isDisabled(),true);failRpc=false;failPrimary=false;await refreshSwap();await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));});
 await check('Stale Ethereum block reads disable financial actions with an explicit refresh path',async()=>{
 try {staleBlocks=true;await refreshSwap();await swap().getByText(/RPC returned stale Ethereum data/).waitFor();assert.equal(await swap().getByRole('button',{name:'MAX',exact:true}).isDisabled(),true);}
 finally {staleBlocks=false;await refreshSwap();await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));}
 });
 await check('Unrelated game RPC failure cannot block swaps or staking',async()=>{failGames=true;await page.reload();await swap().locator('[name="swap-amount"]').fill('0.001');await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));const d=await openStake();await d.locator('[name="staking-amount"]').fill('1');await waitEnabled(d.getByRole('button',{name:'Approve exact PRIO for staking',exact:true}));await page.keyboard.press('Escape');failGames=false;});
 await check('Expired quote refreshes and delayed response cannot become signable under new input',async()=>{await swap().locator('[name="swap-amount"]').fill('0.001');await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));const before=await swap().locator('.swap-details').textContent();await page.evaluate(()=>{window.__realNow=Date.now;Date.now=()=>window.__realNow()+61000;});await page.waitForTimeout(1500);await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));await page.evaluate(()=>Date.now=window.__realNow);assert.match(await swap().locator('.swap-details').textContent(),/seconds remaining/);return {clockAdvancedMs:61000};});
 await check('Insufficient gas is explained before approvals or wallet signatures',async()=>{await page.evaluate(()=>window.__changeWallet(window.__testAccounts[2]));await swap().getByRole('button',{name:'Buy PRIO',exact:true}).click();await swap().locator('[name="swap-amount"]').fill('0.001');await swap().getByText('Insufficient ETH balance. Reduce the amount or add funds.',{exact:true}).waitFor();assert.equal(await primary().isDisabled(),true);assert.equal(await swap().getByRole('button',{name:'MAX',exact:true}).isDisabled(),true);await page.evaluate(()=>window.__changeWallet(window.__testAccounts[0]));});
 await check('Verified owner controls appear only collapsed near footer and preserve Phase A skips',async()=>{await page.evaluate(()=>window.__changeWallet(window.__owner));await page.locator('.founder-section').waitFor({timeout:90000});assert.equal(await page.locator('.founder-section').getAttribute('open'),null);assert.doesNotMatch(await page.locator('.main-nav').innerText(),/Owner|Admin|rounds/);const positions=await page.evaluate(()=>({founder:document.querySelector('.founder-section').offsetTop,staking:document.querySelector('#staking').offsetTop}));assert.ok(positions.founder>positions.staking);await page.locator('.founder-section summary').click();await page.getByRole('button',{name:'Owner setup · Phase A / B',exact:true}).click();await page.getByText('Already correct · skipped',{exact:true}).first().waitFor({timeout:90000});const d=page.getByRole('dialog');assert.match(await d.innerText(),/Already correct|already correct|skipped/i);await page.keyboard.press('Escape');await page.locator('.founder-section summary').click();await page.locator('.founder-section').scrollIntoViewIfNeeded();await save('founder-collapsed.jpg');await page.evaluate(()=>window.__changeWallet(window.__testAccounts[0]));await page.locator('.founder-section').waitFor({state:'hidden'});});
 await check('Practice keyboard flow, reveal recovery, faction reactions, opt-in sound and reduced motion',async()=>{await page.getByRole('button',{name:'Vault Raid · Free practice',exact:true}).click();const d=page.getByRole('dialog');await d.getByRole('button',{name:'Choice 2',exact:true}).focus();await page.keyboard.press('Space');await d.getByRole('button',{name:'Lock choice',exact:true}).click();await d.getByRole('button',{name:'Reveal result',exact:true}).click();assert.match(await d.innerText(),/no PRIO|not a PRIO|PRIO reward/i);await page.keyboard.press('Escape');assert.match(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),/Vault Raid/);for(let i=0;i<4;i++){await page.locator('.faction-card').nth(i).click();assert.equal(await page.locator('.faction-card').nth(i).getAttribute('aria-pressed'),'true');}await page.getByRole('button',{name:'Sound off',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Sound on',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Sound on',exact:true}).click();await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.documentElement.dataset.motion==='off');assert.equal(await page.locator('html').getAttribute('data-motion'),'off');await page.getByRole('button',{name:'Vault Raid · Play with real PRIO',exact:true}).click();await page.getByRole('dialog').locator('.panel-intro').waitFor();assert.match(await page.getByRole('dialog').innerText(),/100 PRIO escrow \+ 2 PRIO fee/);assert.match(await page.getByRole('dialog').innerText(),/secret|backup/i);await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'no-preference'});});
 await check('Mobile staking shortcuts and financial focus remain readable',async()=>{await page.setViewportSize({width:390,height:844});const d=await openStake();await d.locator('[name="staking-amount"]').fill('1');await d.getByRole('button',{name:'50%',exact:true}).focus();const size=await d.getByRole('button',{name:'50%',exact:true}).boundingBox();assert.ok(size.height>=44);await save('staking-mobile.jpg');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.keyboard.press('Escape');await swap().scrollIntoViewIfNeeded();await save('swap-mobile.jpg');});
 await check('Automated accessibility and local font/asset loading on desktop and 320px',async()=>{const results=[];for(const width of [1440,320]){await page.setViewportSize({width,height:1000});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();results.push({width,violations:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});}await writeFile(resolve(artifacts,'axe.json'),JSON.stringify(results,null,2));assert.ok(results.every(r=>!r.violations.length),JSON.stringify(results));assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.resourceFailures,[]);assert.deepEqual(report.consoleErrors,[]);return {fonts:await page.evaluate(()=>[...document.fonts].map(f=>({family:f.family,status:f.status}))),results};});
 await check('Rendered solid financial color contrast and 200% text reflow',async()=>{
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>document.documentElement.style.fontSize='32px');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>document.documentElement.style.fontSize='');
 const values=await page.evaluate(()=>['.swap-panel','.swap-panel .button.primary','.swap-output','.amount-shortcuts button','.gas-note','.action-help'].map(selector=>{const e=document.querySelector(selector),s=getComputedStyle(e);return {selector,color:s.color,background:s.backgroundColor,opacity:s.opacity};}));
 const lum=rgb=>{const n=rgb.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return n[0]*.2126+n[1]*.7152+n[2]*.0722;};
 const result=values.map(v=>{const bg=v.background==='rgba(0, 0, 0, 0)'?'rgb(24, 22, 36)':v.background;const a=lum(v.color),b=lum(bg);return {...v,effectiveBackground:bg,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};});await writeFile(resolve(artifacts,'contrast.json'),JSON.stringify(result,null,2));assert.ok(result.filter(r=>r.opacity==='1').every(r=>r.ratio>=4.5));return result;
 });
 await check('Vault verification failure has an explicit blocker and leaves the verified swap independent',async()=>{
 corruptVault=true;try { await page.locator('.main-nav').getByRole('button',{name:'Staking',exact:true}).click();const d=page.getByRole('dialog');await d.locator('#stake-help').getByText(/Verification failed: vault:/).waitFor({timeout:90000});await d.locator('[name="staking-amount"]').fill('1');assert.equal(await d.getByRole('button',{name:'Approve exact PRIO for staking',exact:true}).isDisabled(),true);assert.match(await d.locator('#stake-help').innerText(),/Stop and review/);await page.keyboard.press('Escape');await swap().getByRole('button',{name:'Buy PRIO',exact:true}).click();await swap().locator('[name="swap-amount"]').fill('0.001');await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));} finally {corruptVault=false;}
 });
 await check('MAX ETH buy executes with an estimated reserve and leaves ETH for gas',async()=>{
 await rpc('anvil_setBalance',[identities[3].address,toHex(parseEther('0.005'))]);await page.evaluate(()=>window.__changeWallet(window.__testAccounts[3]));await waitEnabled(swap().getByRole('button',{name:'MAX',exact:true}));const before=await local.getBalance({address:identities[3].address});await swap().getByRole('button',{name:'MAX',exact:true}).click();const input=parseEther(await swap().locator('[name="swap-amount"]').inputValue());assert.ok(input<before&&input>0n);await waitEnabled(swap().getByRole('button',{name:'Review buy in wallet',exact:true}));await swap().getByRole('button',{name:'Review buy in wallet',exact:true}).click();await waitReceipt(swap());const after=await local.getBalance({address:identities[3].address});assert.ok(after>0n);assert.ok(await balance(identities[3].address)>0n);await page.evaluate(()=>window.__changeWallet(window.__testAccounts[0]));return {initialEthBaseUnits:String(before),inputEthBaseUnits:String(input),remainingEthBaseUnits:String(after)};
 });
 await check('PRIO approvals, deposits and sells explain insufficient gas before requesting a signature',async()=>{
 const account=identities[0].address,eth=await local.getBalance({address:account}),before=report.transactions.length,signatures=await page.evaluate(()=>window.__walletState.signatures);
 try {
  await rpc('anvil_setBalance',[account,'0x0']);await refreshSwap();await swap().getByRole('button',{name:'Sell PRIO',exact:true}).click();await swap().locator('[name="swap-amount"]').fill('100');await swap().getByText(/Insufficient ETH for/).first().waitFor();assert.equal(await primary().isDisabled(),true);
  const d=await openStake();await d.locator('[name="staking-amount"]').fill('1');await d.getByText(/Insufficient ETH for/).first().waitFor();assert.equal(await d.getByRole('button',{name:'Approve exact PRIO for staking',exact:true}).isDisabled(),true);
  // An exact allowance fixture separates deposit gas validation from approval gas validation.
  await page.keyboard.press('Escape');await rpc('anvil_setBalance',[account,toHex(eth)]);
  const hash=await wallets[0].writeContract({address:token,abi:tokenAbi,functionName:'approve',args:[vault,parseEther('1')]});assert.equal((await local.waitForTransactionReceipt({hash})).status,'success');await rpc('anvil_setBalance',[account,'0x0']);
  const deposit=await openStake();await deposit.locator('[name="staking-amount"]').fill('1');await deposit.getByRole('button',{name:'Review deposit in wallet',exact:true}).waitFor();await deposit.getByText(/Insufficient ETH for/).first().waitFor();assert.equal(await deposit.getByRole('button',{name:'Review deposit in wallet',exact:true}).isDisabled(),true);assert.equal(report.transactions.length,before);assert.equal(await page.evaluate(()=>window.__walletState.signatures),signatures);
 } finally {await page.keyboard.press('Escape');await rpc('anvil_setBalance',[account,toHex(eth)]);await refreshSwap();}
 });
 await check('Funded reward claim uses the existing vault and receipt-confirmed UI',async()=>{
 const treasury='0xb68b1ba47734ba91f3fc37164bb39d408908ff7c';
 const fundingHash=await wallets[0].writeContract({address:token,abi:tokenAbi,functionName:'transfer',args:[treasury,parseEther('100')]});assert.equal((await local.waitForTransactionReceipt({hash:fundingHash})).status,'success');
 await rpc('anvil_impersonateAccount',[treasury]);await rpc('anvil_setBalance',[treasury,toHex(parseEther('1'))]);
 const funder=createWalletClient({account:treasury,chain:mainnet,transport:http(endpoint)});const approvalHash=await funder.writeContract({address:token,abi:tokenAbi,functionName:'approve',args:[vault,parseEther('100')]});assert.equal((await local.waitForTransactionReceipt({hash:approvalHash})).status,'success');await local.simulateContract({account:treasury,address:vault,abi:vaultAbi,functionName:'notifyReward',args:[parseEther('100')]});const hash=await funder.writeContract({address:vault,abi:vaultAbi,functionName:'notifyReward',args:[parseEther('100')]});assert.equal((await local.waitForTransactionReceipt({hash})).status,'success');await rpc('evm_increaseTime',[10]);await rpc('evm_mine');
 report.fixtureFunding={fundingHash,notifyRewardHash:hash,amount:'100 PRIO',purpose:'Fork-only external reward funding; existing staked principal was untouched'};
 await page.locator('.main-nav').getByRole('button',{name:'Staking',exact:true}).click();const d=page.getByRole('dialog');await d.getByText('A funded reward stream is active.',{exact:true}).waitFor();const principal=await staked(identities[0].address),before=await balance(identities[0].address);await waitEnabled(d.getByRole('button',{name:'Claim funded rewards',exact:true}));await d.getByRole('button',{name:'Claim funded rewards',exact:true}).click();await waitReceipt(d);assert.ok(await balance(identities[0].address)>before);assert.equal(await staked(identities[0].address),principal);await page.keyboard.press('Escape');return {claimedPrioBaseUnits:String(await balance(identities[0].address)-before)};
 });
}catch(e){report.fatal=String(e.stack||e);console.error(e);}
finally{await browser?.close();if(server)await new Promise(r=>server.close(r));anvil.kill('SIGTERM');report.result=!report.fatal&&report.checks.every(c=>c.passed)?'passed':'failed';report.anvilErrors=anvilError.slice(-1000);report.anvilOutputBytes=anvilOutputBytes;report.rpcFailures=rpcFailures.slice(-20);await writeFile(resolve(artifacts,'results.json'),JSON.stringify(report,null,2));console.log(`${report.checks.filter(c=>c.passed).length}/${report.checks.length} checks passed; ${report.transactions.length} signed local transactions`);if(report.result!=='passed')process.exitCode=1;}
