import { useEffect, useRef, useState } from "react";
import { Trophy, Award, ArrowUpRight } from "lucide-react";
import { hexToString } from "viem";
import type { Snapshot, RoundSnapshot } from "./chain";
import { rankClaims, readSeason, type SeasonResult } from "./chain/seasons";
import { localPractice, GAMES } from "./practice";
import { t } from "./i18n";
import { Badge, ExplorerLink, fmt } from "./ui";
import { message } from "./wallet";
export function SeasonBoard({snapshot:s,stale,rounds,onLive}:{snapshot?:Snapshot;stale:boolean;rounds:RoundSnapshot[];onLive:()=>void}) {
  const [season,setSeason]=useState(new Date().toISOString().slice(0,7));
  const [data,setData]=useState<SeasonResult>();
  const [error,setError]=useState("");
  const [busy,setBusy]=useState(false);
  const [practice,setPractice]=useState(localPractice);
  const abort=useRef<AbortController | undefined>(undefined);
  useEffect(()=>{const onPractice=()=>setPractice(localPractice());window.addEventListener("prism-practice",onPractice);return()=>{window.removeEventListener("prism-practice",onPractice);abort.current?.abort();};},[]);
  const ranks=rankClaims(data?.claims||[]);
  const load=async()=>{
    abort.current?.abort();const controller=new AbortController();abort.current=controller;
    setBusy(true);setError("");setData(undefined);
    try{const result=await readSeason(season,controller.signal);if(!controller.signal.aborted)setData(result);}
    catch(e){if(!controller.signal.aborted)setError(message(e));}
    finally{if(!controller.signal.aborted)setBusy(false);}
  };
  return <section className="section" id="seasons"><div className="section-heading"><div><p className="eyebrow">03 / {t("SEZONLAR & GÖREVLER","SEASONS & CHALLENGES")}</p><h2>{t("GERÇEK SONUÇ.","REAL RESULTS.")} <em>{t("AÇIK KAYIT.","OPEN RECORD.")}</em></h2></div><Trophy size={32}/></div>
    <div className="season-layout"><div className="sub-panel"><h3>{t("PRIO sezon sıralaması","PRIO seasonal leaderboard")}</h3><p>{t("UTC takvim ayları. Sıralama: doğrulanmış Arena Claimed olaylarındaki ödül payı = max(ödeme − 100 PRIO, 0). Emanet iadeleri ve pratik puanları ödül sayılmaz.","UTC calendar months. Rank by verified Arena Claimed prize shares = max(payout − 100 PRIO, 0). Returned escrow and practice scores are excluded.")}</p><label className="field">{t("Sezon (UTC)","Season (UTC)")}<input type="month" name="season" min="2026-10" max={new Date().toISOString().slice(0,7)} value={season} onChange={e=>{abort.current?.abort();setBusy(false);setSeason(e.target.value);setData(undefined);setError("");}}/></label><button className="button secondary" disabled={busy||!s?.verified||stale} onClick={()=>void load()}>{busy?t("Kesinleşmiş kayıtlar doğrulanıyor…","Verifying finalized records…"):t("Sezonu doğrula","Verify season")}</button>
      {error&&<p className="inline-error" role="alert">{t("Geçmiş kayıtlar okunamadı; sıralama oluşturulmadı. Yeniden dene. ","History unavailable; no ranking was generated. Retry. ")}{error}</p>}
      {!data&&<div className="empty-state"><Trophy size={28}/><h4>{s?.arena.roundCount===0n&&!stale?t("Henüz gerçek tur veya ödül yok.","No real rounds or prizes yet."):t("Sezon kayıtlarını doğrula.","Verify season records.")}</h4><p>{t("Sahte oyuncu, puan veya ödül gösterilmez.","No invented players, scores or prizes.")}</p></div>}
      {data&&<><p className="tiny">{data.start.slice(0,10)} ≤ UTC &lt; {data.end.slice(0,10)} · {t("Kesinleşmiş bloklar","Finalized blocks")}: {data.fromBlock.toString()}–{data.throughBlock.toString()}</p>{ranks.length?<div className="table-wrap"><table><thead><tr><th>#</th><th>{t("Oyuncu / rozet","Player / badge")}</th><th>{t("Ödül PRIO","Prize PRIO")}</th><th>{t("Kanıt","Evidence")}</th></tr></thead><tbody>{ranks.map((r,i)=><tr key={r.player}><td>{i+1}</td><td><ExplorerLink address={r.player}/><br/><Badge tone="cyan">{r.prize>0n?t("Fonlanmış ödül aldı","Funded prize claimed"):t("İlk gerçek talep","First real claim")}</Badge></td><td>{fmt(r.prize,6)}</td><td><ExplorerLink tx address={r.receipts[0]} label={t("Makbuz","Receipt")}/></td></tr>)}</tbody></table></div>:<div className="empty-state">{t("Bu sezonda doğrulanmış talep yok. Sıralama boş.","No verified claims in this season. The leaderboard is empty.")}</div>}</>}
      <details className="rules"><summary>{t("Puanlama ve rozet kanıtı","Scoring and badge evidence")}</summary><p>{t("Yalnızca kesinleşmiş bloklar taranır. Her olayın sözleşmesi, başarılı makbuzu, kanonik blok hash'i ve Arena ödemesi karşılaştırılır. Eşit ödülde adres sırası kullanılır. İade olayları puan vermez. Okuma yarıda kalırsa kısmi sıralama yayımlanmaz.","Only finalized blocks are scanned. Each event is checked against its contract, successful receipt, canonical block hash and Arena payout. Ties use address order. Refund events earn no points. Incomplete reads never publish a partial ranking.")}</p><p>{t("Rozetler bilgilendirme amaçlıdır; token değeri veya yeni ödül hakkı vermez.","Badges are informational; they have no token value or new reward rights.")}</p></details>
    </div><div className="challenge-column"><div className="sub-panel"><h3>{t("Yeni meydan okumalar","New challenges")}</h3><p>{t("Ücretli görevler yalnızca zincirde yayımlanmış soru ve kilitli kurallardan gelir. IMD önerileri gerçek operatör incelemesi ve gelecek tur için sahip onayı gerektirir.","Paid challenges come only from published on-chain questions and locked rules. IMD proposals require real operator review and owner approval for a future round.")}</p>{rounds.length?rounds.slice(0,3).map(r=><div className="challenge" key={r.id.toString()}><strong>{GAMES[r.round.mode]?.name} · #{r.id.toString()}</strong><p>{(()=>{try{return r.pinned?hexToString(r.pinned.body).slice(0,240):t("Soru verisi okunamadı.","Question data unavailable.");}catch{return t("İkili soru gövdesini tur ayrıntısında incele.","Inspect the binary question body in round details.");}})()}</p><button className="text-button" onClick={onLive}>{t("Kuralları ve süreleri gör","View rules and deadlines")}<ArrowUpRight size={16}/></button></div>):<div className="empty-state"><p>{t("Yayımlanmış tur yok. Sonraki adım sahip ayarları, operatör ve ödül fonlaması.","No published round. Next: owner setup, operator readiness and prize funding.")}</p></div>}</div>
      <div className="sub-panel"><h3><Award size={20}/> {t("Yerel pratik rozeti","Local practice badge")}</h3><p>{t("Görev: üç oyunda da bir pratik tamamla. Sonuç doğru olmak zorunda değil. Bu yalnızca cihazındaki bir öğrenme kaydıdır.","Challenge: complete one practice in each game. You do not need a correct result. This is only a learning record on your device.")}</p><div className="local-badges">{GAMES.map(g=><Badge key={g.id} tone={practice.includes(g.id)?"cyan":"muted"}>{g.name} · {practice.includes(g.id)?t("Tamamlandı","Completed"):t("Denenmedi","Not tried")}</Badge>)}</div><p className="tiny">{t("Yerel kayıt doğrulanmış sıralamaya girmez. Rozetler token veya ödül hakkı değildir.","Local records never enter verified rankings. Badges confer no tokens or reward rights.")}</p><a className="text-button" href="#arcade">{t("Ücretsiz göreve başla →","Start the free challenge →")}</a></div>
    </div></div>
  </section>;
}
